name = "mailwebhook-mcp"
main = "src/index.ts"
compatibility_date = "2024-10-02"
account_id = "4c1e8515b0682ae4c9897549585a9a28"

# 自定义域名路由 (默认环境)
routes = [
  { pattern = "mailwebhook-mcp-dev.finbase.win", custom_domain = true }
]

# 启用日志
[observability]
enabled = true

# 服务绑定 - qqwebhook Worker (默认环境)
[[services]]
binding = "QQWEBHOOK_SERVICE"
service = "qqwebhook"  # 使用原有的 qqwebhook Worker

# 环境变量
[vars]
MCP_SERVER_NAME = "Mail Webhook MCP Server"
MCP_SERVER_VERSION = "1.0.1"
CORS_ORIGINS = "*"
# 安全配置
RATE_LIMIT_ENABLED = "true"
RATE_LIMIT_WINDOW = "60000"
RATE_LIMIT_MAX_REQUESTS = "60"
AUTH_REQUIRED = "true"

# 生产环境配置
[env.production]
name = "mailwebhook-mcp-prod"
routes = [
  { pattern = "mailwebhook-mcp.finbase.win", custom_domain = true }
]
# 生产环境变量
[env.production.vars]
MCP_SERVER_NAME = "Mail Webhook MCP Server"
MCP_SERVER_VERSION = "1.0.0"
CORS_ORIGINS = "*"
RATE_LIMIT_ENABLED = "true"
RATE_LIMIT_WINDOW = "60000"
RATE_LIMIT_MAX_REQUESTS = "60"
AUTH_REQUIRED = "true"
# 生产环境的服务绑定
[[env.production.services]]
binding = "QQWEBHOOK_SERVICE"
service = "qqwebhook"  # 使用原有的 qqwebhook Worker

# 开发环境配置
[env.dev]
name = "mailwebhook-mcp-dev"
vars = { CORS_ORIGINS = "http://localhost:3000,http://localhost:8080" }
# 开发环境的服务绑定
[[env.dev.services]]
binding = "QQWEBHOOK_SERVICE"
service = "qqwebhook-dev"  # 开发环境的 qqwebhook Worker